name = "CobbleCult Modpack"
author = "wamulet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96772e0dca426fa4f75dad889187577e8e59a70631d4f642e0d7ccfe407f7103"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
