name = "CobbleCult Modpack"
author = "wamulet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8572462b01741c82a610912c0462da07ae629f94e52b218fa0b8bf45532f0dd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
