name = "CobbleCult Modpack"
author = "wamulet"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df6e3cea5c301b358b79815fd164443b40ee99179b1410c316c977cebbb2fcb8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
